### ISSUE TITLE
Package 'method_source' version conflicts with newer version of pry

### ISSUE THREAD

**Issue by peter50216** [peter50216/pwntools-ruby#227]
pry version `0.13.0` depends on `method_source ~> 1.0`, but pwntools-ruby use `~> 0.9`. This cause an error when trying to `require "pwn"` inside newer version of pry:

```
[1] pry(main)> require 'pwn'
Gem::ConflictError: Unable to activate pwntools-1.2.0, because method_source-1.0.0 conflicts with method_source (~> 0.9)
from ~/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/specification.rb:2243:in `raise_if_conflicts'
Caused by Gem::ConflictError: Unable to activate pwntools-1.2.0, because method_source-1.0.0 conflicts with method_source (~> 0.9)
from ~/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/specification.rb:2243:in `raise_if_conflicts'
Caused by LoadError: cannot load such file -- pwn
from ~/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
```

**Comment by david942j** [comment]
I remember I also faced a conflict error even when I use `method_source ~> 1.0` for pwntools-ruby (it happened during DEF CON, can't tell what exactly I did). Considering change it to `>= 0.9`
