### ISSUE TITLE
incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)

### ISSUE THREAD

**Issue by rkaaine** [peter50216/pwntools-ruby#94]
Tested on OSX 10.13.3 and Ubuntu 16.04, both using Ruby version 2.4.3 and pwntools-1.0.1 from master branch using example provided on pwntools-ruby project Github homepage.

[DEBUG] Received 0x14 bytes:
    00000000  4c 65 74 27  73 20 73 74  61 72 74 20  74 68 65 20  │Let'│s st│art │the │
    00000010  43 54 46 3a                                         │CTF:│
    00000014
[DEBUG] Sent 0x18 bytes:
    00000000  41 41 41 41  41 41 41 41  41 41 41 41  41 41 41 41  │AAAA│AAAA│AAAA│AAAA│
    00000010  41 41 41 41  87 80 04 08                            │AAAA│····│
    00000018
[DEBUG] Received 0x14 bytes:
    00000000  20 a7 c1 ff  01 00 00 00  38 af c1 ff  00 00 00 00  │ ···│····│8···│····│
    00000010  4a af c1 ff                                         │J···│
    00000014
/Users/sp00k/.rvm/gems/ruby-2.4.3/gems/pwntools-1.0.1/lib/pwnlib/tubes/tube.rb:148:in `index': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
	from /Users/sp00k/.rvm/gems/ruby-2.4.3/gems/pwntools-1.0.1/lib/pwnlib/tubes/tube.rb:148:in `block (2 levels) in recvuntil'
	from /Users/sp00k/.rvm/gems/ruby-2.4.3/gems/pwntools-1.0.1/lib/pwnlib/tubes/tube.rb:147:in `each'
	from /Users/sp00k/.rvm/gems/ruby-2.4.3/gems/pwntools-1.0.1/lib/pwnlib/tubes/tube.rb:147:in `block in recvuntil'
	from /Users/sp00k/.rvm/gems/ruby-2.4.3/gems/pwntools-1.0.1/lib/pwnlib/timer.rb:54:in `countdown'
	from /Users/sp00k/.rvm/gems/ruby-2.4.3/gems/pwntools-1.0.1/lib/pwnlib/tubes/tube.rb:131:in `recvuntil'
	from ./start.rb:9:in `<main>'

**Comment by rkaaine** [comment]
My mistake, didn't include the:
# encoding: ASCII-8BIT
